## play to merge  a release back into master + dev, tag push and delete release branch.
## BE SURE to use git protocol AND be sure to have your private key saved as /root/.ssh/id_rsa
---
- hosts: all
  become: yes
  vars:
    # lsulibraries_modules_updated:
    #   - { dest: "/sites/all/modules/about-ldc/", repo: "lsulibraries/about-ldc" }
    git_actions:
      - git fetch tmp
      - git stash
      - "git checkout --track tmp/release-{{ ldl_release }}"
      - "git pull tmp release-{{ ldl_release }}"
      - git checkout --track tmp/master
      - git pull tmp master
      - "git merge --no-ff --no-commit release-{{ ldl_release }}"
      - "git commit -m 'Merges branch release-{{ ldl_release }}'"
      - git push tmp :release-{{ ldl_release }}
      - "git tag release-{{ ldl_release }}"
      - git push tmp --tags master
      - git checkout --track tmp/develop
      - git pull tmp develop
      - "git merge master"
      # - "git commit -m 'Merges latest from master'"
      - git push tmp develop

    git_just_tag_actions:
      - git fetch tmp
      - git stash
      - git checkout develop
      - git pull origin develop
      - "git tag release-{{ ldl_release }}"
      # - git push origin --tags
  tasks:

    - name: add temp remote using git protocol
      command: "git remote add tmp {{ lsulibraries_gh_protocol }}{{ item.repo }}"
      args:
        chdir: "{{ drupal_core_path }}{{ item.dest }}"
      with_items:
        - "{{ lsulibraries_modules_updated }}"
      ignore_errors: yes

    - name: close release
      command: "{{ item[1] }}"
      args:
        chdir: "{{ drupal_core_path }}{{ item[0].dest }}"
      with_nested:
        - "{{ lsulibraries_modules_updated }}"
        - "{{ git_just_tag_actions }}"
