---
- hosts: all
  become: yes
  vars:
    git_actions:
      - git fetch origin
      - git checkout develop
      - git pull origin develop
      - "git checkout -b release-{{ ldl_release }}"
      - "git push origin release-{{ ldl_release }}"
      # - git checkout master
      # - "git merge --no-commit --no-ff release-{{ ldl_release }}"
      # - "git commit -m 'Merges '"
  tasks:
    - name: create release
      command: "{{ item[1] }}"
      args:
        chdir: "{{ drupal_core_path }}{{ item[0].dest }}"
      with_nested:
        - "{{ lsulibraries_modules_updated }}"
        - "{{ git_actions }}"
