- hosts: all
  become: yes
  vars:
    mysql_login_host: localhost

  roles:
    # - ansible-role-mysql

  tasks:

    - name: setup apt repo for mysql v5.6
      apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu trusty universe

    - name: install old 5.6 mysql
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - mysql-server-5.6
        - mysql-client-5.6
        - python3-pip
        - python3-mysqldb

    - name: Ensure databases exist.
      mysql_db:
        login_host: "{{ mysql_login_host }}"
        login_user: "{{ mysql_login_user }}"
        login_password: "{{ mysql_login_password }}"
        state: present
        encoding: utf8mb4
        name: "{{ item }}"
      with_items:
        - "{{ fedora_database_name }}"
        - "{{ islandora_database_name }}"

    - name: Ensure fcrepo user exists.
      mysql_user:
        login_host: "{{ mysql_login_host }}"
        login_user: "{{ mysql_login_user }}"
        login_password: "{{ mysql_login_password }}"
        state: present
        name: "{{ fedora_database_user }}"
        password: "{{ fedora_database_pass }}"
        priv: "{{ fedora_database_name }}.*:ALL"


    - name: Ensure islandora user exists.
      mysql_user:
        login_host: "{{ mysql_login_host }}"
        login_user: "{{ mysql_login_user }}"
        login_password: "{{ mysql_login_password }}"
        state: present
        name: "{{ islandora_database_user }}"
        password: "{{ islandora_database_pass }}"
        host: "{{ item }}"
        priv: "{{ islandora_database_name }}.*:ALL"
      with_items:
        - localhost
        - "{{ frontend_ip }}"
