- hosts: all
  become: yes

  gather_facts: false
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python python-simplejson
    - action: setup # https://stackoverflow.com/a/40790418/3294778

  roles:
    - common
    - ansible-role-solr

  tasks:
    - include_tasks: common.yml
