# system.yml

#########################################################################
#### Run system-level commands here, such as : copying files around, ####
#### setting up cron or monitoring configs, updating logging prefs.  ####
####                                                                 ####
#########################################################################

# - name: set permissions.
#   shell: "sh /opt/scripts/drupal-permissions/drupal-fix-permissions.sh --drupal_path={{ drupal_core_path }} --drupal_user=root --httpd_group=www-data"
#   when: environment_type != 'dev'

##  Restart tomcat to pick up changes in xyz
# - name: Restart tomcat
#   service:
#     name: tomcat7
#     state: restarted

  ## If present, causes later git checkout to fail (it's tracked in the current version).
- name: Remove untracked xml in drupal module.
  file:
    path: "{{ drupal_core_path }}/sites/all/modules/islandora_xml_forms/builder/self_transforms/blankNodes.xsl"
    state: absent

- name: Get current curl version.
  shell: curl --version
  register: curl_version

- name: get new version of curl
  unarchive:
    remote_src: yes
    src: http://curl.haxx.se/download/curl-7.57.0.tar.gz
    dest: /opt/
    validate_certs: no
  when: curl_version.stdout.find ('7.57.0') == -1

- name: Build curl
  command: "{{ item }}"
  args:
    chdir: /opt/curl-7.57.0
  with_items:
    - ./buildconf
    - ./configure
    - make
    - make install
    - ldconfig
  when: curl_version.stdout.find ('7.57.0') == -1

- name: link the new curl
  file:
    state: link
    src: /usr/local/bin/curl
    dest: /usr/bin/curl
    force: yes
  when: curl_version.stdout.find ('7.57.0') == -1

- name: ensure xhprof is not enabled in production
  file:
    path: /etc/php5/apache2/conf.d/xhprof.ini
    state: absent
  when: environment_type != 'dev'
