#!/bin/bash

# command curl -sSL https://rvm.io/mpapis.asc | sudo gpg --import -
# \curl -L https://get.rvm.io | bash -s stable --ruby
# source /usr/local/rvm/scripts/rvm
# gem install sass

## I had to run this manually from the cli `source /usr/local/rvm/scripts/rvm`

## consider adding --watch

# thanks to https://stackoverflow.com/questions/23493984/how-to-install-ruby-2-and-ruby-gems-on-ubuntu-box-with-ansible !!

- name: Purge whatever ruby2 is there
  apt:
    pkg: ruby2.0
    purge: yes
    state: absent

- name: Latest version of Ruby is installed
  apt:
    pkg: "{{ item }}"
    update_cache: yes
  with_items:
    - ruby2.0=2.0.0.484-1ubuntu2
    - ruby2.0-dev
    - libruby2.0=2.0.0.484-1ubuntu2

- name: Symlink exists for Ruby 2.0
  file: src=/usr/bin/ruby2.0 dest=/usr/local/bin/ruby state=link

- name: Symlink exists for Ruby Gems 2.0
  file: src=/usr/bin/gem2.0 dest=/usr/local/bin/gem state=link

- name: downgrade psych, per https://bugs.launchpad.net/ubuntu/+source/ruby2.0/+bug/1777174/comments/3
  command: gem install psych --version 2.0.17

- name: install sass
  command: gem install sass

- name: run sass
  shell:  (sudo nohup sass --watch /var/www/ldl/sites/all/themes/ldl/css/global.scss:/var/www/ldl/sites/all/themes/ldl/css/global.css  </dev/null >/dev/null 2>&1 & sleep 1)
