# finish.yml

#########################################################################
#### Steps to run at the very end of provisioning,                   ####
####    but before ingesting sample collections, if set in all.yml.  ####
####                                                                 ####
#########################################################################

- name: clear cache
  command: drush cc all
  args:
    chdir: '{{ drupal_core_path }}'

- name: feature revert
  command: drush fra -y
  args:
    chdir: '{{ drupal_core_path }}'

- name: set permissions.
  shell: "sh /opt/scripts/drupal-permissions/drupal-fix-permissions.sh --drupal_path={{ drupal_core_path }} --drupal_user=root --httpd_group=www-data"
  when: environment_type != 'dev'

- name: Set permissions for dev.
  file:
    path: "{{ drupal_core_path }}/"
    owner: vagrant
    group: vagrant
    mode: 0755
    recurse: yes
  when: environment_type == 'dev'

# reverting manually after the build cleared GUI 'overridden' status.
- name: feature revert
  command: drush fra -y
  args:
    chdir: '{{ drupal_core_path }}'
