# finish.yml

#########################################################################
#### Steps to run at the very end of provisioning,                   ####
####    but before ingesting sample collections, if set in all.yml.  ####
####                                                                 ####
#########################################################################

- name: feature revert
  command: drush fra -y
  args:
    chdir: '{{ drupal_core_path }}'

- name: clear cache
  command: drush cc all
  args:
    chdir: '{{ drupal_core_path }}'

- name: set permissions.
  shell: "sh /opt/scripts/drupal-permissions/drupal-fix-permissions.sh --drupal_path={{ drupal_core_path }} --drupal_user=root --httpd_group=www-data"
  when: environment_type != 'dev'
