# modules.yml

#########################################################################
#### Clone, drush dl, drush en, drush dis drupal modules.            ####
####                                                                 ####
#### This play relies totally on the variables set in all.yml.       ####
#########################################################################

- name: update core modules
  git:
    repo: "{{ item.repo }}"
    dest: '{{drupal_core_path}}{{ item.dest }}'
    force: true
    version: "{{ islandora_core_version }}"
  with_items: "{{ islandora_core_modules }}"

- name: update ldl stable modules
  git:
    repo: "{{ item.repo }}"
    dest: '{{drupal_core_path}}{{ item.dest }}'
    force: true
    version: "{{ ldl_major_version }}"
  with_items: "{{ lsulibraries_stable_modules }}"

- name: update ldl updated modules
  git:
    repo: "{{ item.repo }}"
    dest: '{{drupal_core_path}}{{ item.dest }}'
    force: true
    version: "{{ ldl_release_version }}"
  with_items: "{{ lsulibraries_modules_updated }}"

- name: Get git repos.
  git:
    repo: "{{ item.repo }}"
    dest: '{{drupal_core_path}}{{ item.dest }}'
    force: true
    version: "{{ item.version }}"
  with_items: "{{ other_modules }}"

- name: Download drupal contribs.
  command: "drush dl -y {{ item }}"
  args:
    chdir: '{{ drupal_core_path }}'
  with_items: "{{ drush_dl }}"

- wait_for:
    host: 192.168.111.111
    port: 8080
  when: environment_type == 'dev'

- name: remove old submod block_setting_ldl_theme
  file:
    path: "{{ drupal_core_path }}/sites/all/modules/islandora-features/block_setting_ldl_theme"
    state: absent

- name: Enable modules.
  command: "drush -u 1 -y en {{ item }}"
  args:
    chdir: "{{ drupal_core_path }}"
  with_items: "{{ drush_en }}"

- name: Disable unsued modules.
  command: "drush dis -y {{ item }}"
  args:
    chdir: '{{ drupal_core_path }}'
  with_items: "{{ drush_dis }}"

- name: Update drupal db.
  command: drush -y updatedb
  args:
    chdir: '{{ drupal_core_path }}'

- name: install deps with composer for RR
  command: composer install
  args:
    chdir: "{{ drupal_core_path }}/sites/all/modules/islandora_solution_pack_remote_resource/modules/islandora_remote_resource_batch"
