# modules.yml

#########################################################################
#### Clone, drush dl, drush en, drush dis drupal modules.            ####
####                                                                 ####
#### This play relies totally on the variables set in all.yml.       ####
#########################################################################

- name: Get git repos.
  git:
    repo: "{{ item.repo }}"
    dest: '{{drupal_core_path}}{{ item.dest }}'
    force: true
    version: "{{ item.version }}"
  with_items: "{{ git_versions }}"

- name: Download drupal contribs.
  command: "drush dl -y {{ item }}"
  args:
    chdir: '{{ drupal_core_path }}'
  with_items: "{{ drush_dl }}"

- wait_for:
    host: 192.168.111.111
    port: 8080

- name: Enable modules.
  command: "drush -u 1 -y en {{ item }}"
  args:
    chdir: "{{ drupal_core_path }}"
  with_items: "{{ drush_en }}"

- name: Disable unsued modules.
  command: "drush dis -y {{ item }}"
  args:
    chdir: '{{ drupal_core_path }}'
  with_items: "{{ drush_dis }}"

- name: Update drupal db.
  command: drush -y updatedb
  args:
    chdir: '{{ drupal_core_path }}'
