# system.yml

#########################################################################
#### Run system-level commands here, such as : copying files around, ####
#### setting up cron or monitoring configs, updating logging prefs.  ####
####                                                                 ####
#########################################################################

# - name: set permissions.
#   shell: "sh /opt/scripts/drupal-permissions/drupal-fix-permissions.sh --drupal_path={{ drupal_core_path }} --drupal_user=root --httpd_group=www-data"
#   when: environment_type != 'dev'

##  Restart tomcat to pick up changes in xyz
# - name: Restart tomcat
#   service:
#     name: tomcat7
#     state: restarted

- name: get new version of curl
  unarchive:
    remote_src: yes
    src: http://curl.haxx.se/download/curl-7.57.0.tar.gz
    dest: /opt/
    validate_certs: no


- name: Build curl
  command: "{{ item }}"
  args:
    chdir: /opt/curl-7.57.0
  with_items:
    - ./buildconf
    - ./configure
    - make
    - make install
    - ldconfig

- name: link the new curl
  file:
    state: link
    src: /usr/local/bin/curl
    dest: /usr/bin/curl
    force: yes
