# system.yml

#########################################################################
#### Run system-level commands here, such as : copying files around, ####
#### setting up cron or monitoring configs, updating logging prefs.  ####
####                                                                 ####
#########################################################################

# - name: set permissions.
#   shell: "sh /opt/scripts/drupal-permissions/drupal-fix-permissions.sh --drupal_path={{ drupal_core_path }} --drupal_user=root --httpd_group=www-data"
#   when: environment_type != 'dev'

##  Restart tomcat to pick up changes in xyz
# - name: Restart tomcat
#   service:
#     name: tomcat7
#     state: restarted