# vsets.yml

#########################################################################
####  Set any Drupal vars here.                                      ####
#########################################################################

- name: Set simple key => val variables.
  command: drush -u 1 vset {{ item.key }} {{ item.value }}
  args:
    chdir: "{{ drupal_core_path }}"
  with_items: "{{ drush_vset_simple }}"

#########################################################################
#### other ways to vset that are less easy to automate in this play. ####
#########################################################################

# - name: 'Set update_notify_emails to something other than example.com. ## 2016101311'
#   command: drush vset --format=json update_notify_emails '["admin@example.com"]'
#   args:
#     chdir: "{{ drupal_core_path }}"

# - name: 'Set reroute enabled. ## 2016101311'
#   command: drush vset reroute_email_enable 1
#   args:
#     chdir: "{{ drupal_core_path }}"
#   when: environment_type != "production"

- name: configure seadragon
  args:
    chdir: "{{ drupal_core_path }}/sites/ldl"
  command: "drush -u 1 ev \"variable_set(\'islandora_openseadragon_settings\', {{ seadragon_settings }})\""

- name: set collection display query language
  args:
    chdir: "{{ drupal_core_path  }}"
  command: "drush vset islandora_basic_collection_display_backend: islandora_solr_query_backend"

- name: set collection display query field and order
  args:
    chdir: "{{ drupal_core_path  }}"
  command: "drush vset islandora_solr_collection_sort: 'mods_titleInfo_title asc'"


